spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/school_app
spring.datasource.username=postgres
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.jwt.secret=6d4A78433972517a4e6d577174477a77326d3578703473367639794142434445
app.jwt.expiration-ms=86400000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB